### ISSUE TITLE
Certificate issue

### ISSUE THREAD

**Issue by IzzySoft** [projectdelta6/ADB-Stay-Awake#4]
A scan ([see here](https://gitlab.com/IzzyOnDroid/repo/-/issues/477) for details and background) just revealed the APKs at your releases are signed using a debug key. As that has security implications, may I ask you to please switch to a proper release key, and provide the corresponding APK signed with it? Thanks in advance!

**Comment by projectdelta6** [comment]
I've uploaded a new APK that is signed with a release key, this will cause issues for people trying to update from the old one, they will likely need to uninstall that one first.

**Comment by IzzySoft** [comment]
```
$ iod repo get com.duck.stayawakeadb
No metadata file (yml) for 'com.davenet.notely', skipping
com.duck.stayawakeadb: looking for 'https://api.github.com/repos/projectdelta6/ADB-Stay-Awake/releases'
getGithubLastRel: no releases found; tags is null for com.duck.stayawakeadb
```

Looks like you removed all releases. Err… looks like my settings are confused: they have `guthub-releases` and an URL for inside the repo :see_no_evil: OK, fixed that to `github-repo` – and now the updater finds the APK. Should you one day move the APKs to `releases/` please let me know so I adjust that accordingly here (the pro of that is they don't unnecessarily "bloat" your repository while still being easy to access).

> this will cause issues for people trying to update from the old one

Yes, that cannot be avoided. But it can be clearly pointed out:

![image](https://github.com/projectdelta6/ADB-Stay-Awake/assets/6781438/ae3411d6-fe5e-4f42-b932-7f66f4985a7f)

That "WhatsNew" is controlled via per-release-changelogs in Fastlane. If you want to, I can open a PR sending you what is set up for your app here – and you're welcome to build on that e.g. using my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) :wink:

Thanks a lot, looks fine now!
